# Generated by Django 4.0.6 on 2022-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='methodTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_title', models.CharField(max_length=200)),
                ('method_description', models.TextField()),
                ('publicationDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
